Models/Bowler.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Mission13.Models
{
    public class Bowler
    {
        [Key]
        [Required]
        public int BowlerID { get; set; }
        public string BowlerLastName { get; set; }
        public string BowlerFirstName { get; set; }   
        public string BowlerMiddleInit { get; set; }
        public string BowlerAddress { get; set; }
        public string BowlerCity { get; set; }
        public string BowlerState { get; set; }
        public string BowlerZip { get; set; }
        public string BowlerPhoneNumber { get; set; }
        public int TeamID { get; set; }
    }
}

Models/BowlerDBContext.cs
using System;
using Microsoft.EntityFrameworkCore;

namespace Mission13.Models
{
    public class BowlerDBContext : DbContext
    {
        public BowlerDBContext(DbContextOptions<BowlerDBContext> options) : base(options)
        {
        }

        public DbSet<Bowler> Bowlers { get; set; }
        public DbSet<Team> Teams { get; set; }
    }
}

Models/EFBowlerRepository.cs
using System;
using System.Linq;

namespace Mission13.Models
{
    public class EFBowlerRepository : IBowlerRepository
    {
        private BowlerDBContext _context { get; set; }

        public EFBowlerRepository(BowlerDBContext temp)
        {
            _context = temp;
        }

        public IQueryable<Bowler> Bowlers => _context.Bowlers;
        public IQueryable<Team> Teams => _context.Teams;

        public void Add(Bowler b)
        {
            _context.Add(b);
            _context.SaveChanges();
        }

        public void Edit(Bowler b)
        {
            _context.Update(b);
            _context.SaveChanges();
        }

        public void Delete(Bowler b)
        {
            _context.Bowlers.Remove(b);
            _context.SaveChanges();
        }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Mission13.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/IBowlerRepository.cs
using System;
using System.Linq;

namespace Mission13.Models
{
    public interface IBowlerRepository
    {
        IQueryable<Bowler> Bowlers { get; }
        IQueryable<Team> Teams { get; }
        void Add(Bowler b);
        void Edit(Bowler b);
        void Delete(Bowler b);
    }
}

Models/Team.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Mission13.Models
{
    public class Team
    {
        [Key]
        [Required]
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public int CaptainID { get; set; }
    }
}

Components/TeamsViewComponent.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Mission13.Models;

namespace Mission13.Components
{
    public class TeamsViewComponent : ViewComponent
    {
        private IBowlerRepository _repo { get; set; }

        public TeamsViewComponent(IBowlerRepository temp)
        {
            _repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            var id = RouteData?.Values["teamID"];
            ViewBag.SelectedType = RouteData?.Values["teamID"];

            var teams = _repo.Teams
                .OrderBy(x => x.TeamName);

            var team = teams.FirstOrDefault(x => x.TeamID.ToString() == id);                                        

            if (team != null)
            {
                ViewBag.SelectedTeam = team.TeamName;
            }


            return View(teams);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Mission13.Models;

namespace Mission13.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private IBowlerRepository _repo { get; set; }

        public HomeController(ILogger<HomeController> logger, IBowlerRepository temp)
        {
            _logger = logger;
            _repo = temp;
        }

        public IActionResult Index(int? teamID)
        {
            if (teamID == null)
            {
                var bowlers = _repo.Bowlers
                    .OrderBy(x => x.BowlerFirstName)
                    .ToList();
                return View(bowlers);
            }
            else
            {
                var bowlers = _repo.Bowlers
                    .Where(x => x.TeamID == teamID)
                    .OrderBy(x => x.BowlerFirstName)
                    .ToList();
                return View(bowlers);
            }
        }

        [HttpGet]
        public IActionResult BowlerForm()
        {
            ViewBag.teams = _repo.Teams.Distinct().ToList();

            return View();
        }

        [HttpPost]
        public IActionResult BowlerForm(Bowler b)
        {
            b.BowlerID = _repo.Bowlers.ToList().LastOrDefault().BowlerID + 1;
            _repo.Add(b);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.teams = _repo.Teams.Distinct().ToList();

            var bowler = _repo.Bowlers.Single(x => x.BowlerID == id);

            return View("BowlerForm", bowler);
        }

        [HttpPost]
        public IActionResult Edit(Bowler b)
        {            
            _repo.Edit(b);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var bowler = _repo.Bowlers.Single(x => x.BowlerID == id);

            return View(bowler);
        }

        [HttpPost]
        public IActionResult Delete(Bowler b)
        {
            _repo.Delete(b);

            return RedirectToAction("Index");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/BowlerForm.cshtml
@{
    ViewData["Title"] = "Bowler Form";
}
@model Mission13.Models.Bowler

<h1>Fill Out Appointment Info</h1>

<div>
    <form method="post">

        <div asp-validation-summary="All"></div>

        <input type="hidden" asp-for="BowlerID"/>

        <label asp-for="BowlerFirstName">First Name:</label><br />
        <input asp-for="BowlerFirstName" /><br />

        <label asp-for="BowlerLastName">Last Name:</label><br />
        <input asp-for="BowlerLastName" /><br />

        <label asp-for="BowlerMiddleInit">Middle Initial:</label><br />
        <input asp-for="BowlerMiddleInit" /><br />

        <label asp-for="BowlerAddress">Address:</label><br />
        <input asp-for="BowlerAddress" /><br />

        <label asp-for="BowlerCity">City:</label><br />
        <input asp-for="BowlerCity" /><br />

        <label asp-for="BowlerState">State:</label><br />
        <input asp-for="BowlerState" /><br />

        <label asp-for="BowlerZip">Zip:</label><br />
        <input asp-for="BowlerZip" /><br />

        <label asp-for="BowlerPhoneNumber">Phone Number:</label><br />
        <input asp-for="BowlerPhoneNumber" /><br />

        <label asp-for="TeamID">Team:</label>
        <select asp-for="TeamID">
            @foreach(Team t in ViewBag.teams)
            {
                <option value="@t.TeamID">@t.TeamName</option>
            }
        </select>

        <br />

        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
</div>

Views/Home/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Delete Bowler";
}

@model Bowler

<h2>Confirm Deletion</h2>
<h3>Are you sure you want to delete the record for @Model.BowlerFirstName @Model.BowlerLastName?</h3>

<form method="post" asp-action="Delete">
    <button type="submit" class="btn btn-secondary">Delete</button>
    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Cancel</a>

    <input type="hidden" asp-for="BowlerID" />
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model List<Bowler>



<div class="row m-1 p1">
    <div class="col-3" id="teams">
        <vc:teams></vc:teams>
    </div>

    <main class="col-9">

        <a class="btn btn-primary" asp-controller="Home" asp-action="BowlerForm">Add Bowler</a>
        <br />
        <div>
            <table class="table table-bordered table-striped">

                <thead>
                    <tr>
                        <th>First Name</th>
                        <th>Middle Initial</th>
                        <th>Last Name</th>
                        <th>Address</th>
                        <th>City</th>
                        <th>State</th>
                        <th>Zip</th>
                        <th>Phone Number</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var b in Model)
                    {
                        <tr>
                            <td>@b.BowlerFirstName</td>
                            <td>@b.BowlerMiddleInit</td>
                            <td>@b.BowlerLastName</td>
                            <td>@b.BowlerAddress</td>
                            <td>@b.BowlerCity</td>
                            <td>@b.BowlerState</td>
                            <td>@b.BowlerZip</td>
                            <td>@b.BowlerPhoneNumber</td>
                            <td> <a class="btn btn-primary" asp-controller="Home" asp-action="Edit" asp-route-id="@b.BowlerID">Edit</a></td>
                            <td><a class="btn btn-danger" asp-controller="Home" asp-action="Delete" asp-route-id="@b.BowlerID">Delete</a></td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>
    </main>
</div>

Views/Shared/Components/Teams/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IEnumerable<Team>

<div class="d-grid gap-2">
    <h2>@ViewBag.SelectedTeam</h2>
    <a asp-controller="Home" asp-action="Index" asp-route-teamID="" class="btn btn-outline-secondary">Home</a>
    <br />
    @foreach (var t in Model)
    {
        <a asp-controller="Home" asp-action="Index" asp-route-teamID="@t.TeamID"
           class="btn @(ViewBag.SelectedType == t.TeamID.ToString() ? "btn-primary" : "btn-outline-secondary")">@t.TeamName</a>
        <br />
    }
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mission13</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mission13</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Mission13 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>